custom

diff --git a/vagrantfiles/centos/common b/vagrantfiles/centos/common
--- a/vagrantfiles/centos/common
+++ b/vagrantfiles/centos/common
@@ -16,6 +16,23 @@ systemctl stop firewalld || true
 systemctl disable firewalld || true
 systemctl mask firewalld || true
 
+retries=5
+for ((i=1; i<=retries; i++)); do
+    curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
+    yum clean all && \
+    yum makecache && \
+    yum -y install ipset ipvsadm tcpdump curl wget && \
+    break
+    [[ $retries -eq i ]] && { echo "Failed to install hg after 5 tries"; exit 1; }
+done
+
+for ((i=1; i<=retries; i++)); do
+    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
+    yum install jq -y && break
+
+    [[ $retries -eq i ]] && { echo "Failed to install hg after 5 tries"; exit 1; }
+done
+
 if [ -n '#{INSTALL_ADDITIONAL_PACKAGES}' ]; then
     yum clean packages
     retries=5
@@ -37,7 +54,7 @@ for ((i=1; i<=retries; i++)); do
         lvm2
     yum-config-manager \
         --add-repo \
-        https://download.docker.com/linux/centos/docker-ce.repo
+        http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
     yum install -y docker-ce docker-ce-cli containerd.io && \
         break
 
